name: Build Rectify11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          lfs: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Restore NuGet Packages
        run: |
          nuget restore Rectify11Installer.sln
          nuget restore Rectify11ControlCenter\Rectify11ControlCenter.sln

      - name: Build Rectify11 Control Center
        run: msbuild Rectify11ControlCenter\Rectify11ControlCenter.sln /p:Configuration=Release

      - name: Build Rectify11 Installer
        run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:Platform=x64

      - name: Create Single EXE (using ILRepack)
        run: |
          mkdir Rectify11Installer\bin\output\Release
          Rectify11Installer\ILRepack.exe \
            Rectify11Installer\bin\Release\Rectify11Installer.exe \
            /out:Rectify11Installer\bin\output\Release\Rectify11Installer.exe \
            Rectify11Installer\bin\Release\libmsstyle.dll \
            Rectify11Installer\bin\Release\TaskDialog.dll

      - name: Upload Rectify11 Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rectify11Installer (x64)
          path: Rectify11Installer\bin\output\Release\Rectify11Installer.exe
